### ISSUE TITLE
C++ compiler

### ISSUE THREAD

**Issue by ClaudeNovaMB** [brakmic/Bitcoin_Full_Node_on_Raspberry_Pi3#1]
Hi there,
Ive followed the steps in your book and stuck on page 119.
./configure LDFLAGS+....... returns saying the C++ compiler tested no and c++ compiler cant create executables. 
Not sure how to continue past this. Flashed NOOBS latest version and followed all other steps without problems
Would appreciate your input pls

**Comment by brakmic** [comment]
GitHub is the wrong place for user support questions. In general, I don't offer free consulting support. Please, check your compiler configuration and Linux environment.
